language: generic
dist: bionic
group: edge

jobs:
  include:
    - stage: ":ship: it"
      script: make ship
      if: (branch = master and type = push ) OR commit_message =~ /ship:docker/ OR env(SHIP_DOCKER) = true
